const mapboxl = require("mapbox-gl/dist/mapbox-gl.js");
import mapboxgl from 'mapbox-gl';
import { useState, useEffect } from 'react';


export default function Mapbox(){
    const [Map, setMap]=useState();
    
    mapboxgl.accessToken = 'pk.eyJ1IjoiYWJ5YmxhY2ttb3V0aCIsImEiOiJjbGFodTBobmowODIwM3hvYmxva20zYWQ4In0.GWgmsYW9P5xUKzxDGliiVg';

    useEffect(()=>{
        const map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/light/v10',
            center: [-77.034084,38.909671],
            zoom: 13,
            scrollZoom: false
        });
        setMap(map);
    },[])


    return(
        <div  className={styles.container} >
            <Head>
                <title>Mapbox Store Location</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico" />
                <link href='https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css' rel='stylesheet' />
           </Head>

        <main  className={styles.main}>
            <div className="sidebar">
                <div className="heiding">
                    <h1>Our Locations</h1>
                </div>
                <div id="listings" className="listings"></div>
            </div>
                <div id="map" className="map"></div>
        </main>
        <script src='https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js'></script>
        
        </div>

    )
}
